param()
$src = "csv_out/features_utf8.csv"
$out = "csv_out/features_kano.csv"
$rows = Import-Csv -Path $src -Encoding UTF8
function Get-Jitter($text){ $md5 = [System.Security.Cryptography.MD5]::Create(); $bytes = [System.Text.Encoding]::UTF8.GetBytes($text); $hash = $md5.ComputeHash($bytes); $u1 = [System.BitConverter]::ToUInt32($hash,0); $u2 = [System.BitConverter]::ToUInt32($hash,4); $r1 = $u1 / [uint32]::MaxValue; $r2 = $u2 / [uint32]::MaxValue; $dx = (($r1*2)-1)*0.04; $dy = (($r2*2)-1)*0.04; return ,@($dx,$dy) }
function Clamp([double]$v){ if($v -lt 0){return 0} if($v -gt 1){return 1} return [math]::Round($v,3) }
function Classify([string]$text){ if ([string]::IsNullOrWhiteSpace($text)) { return ,@("Indifferent",0.5,0.5,"空白") } $reverse = '强制.*弹窗|频繁.*弹窗|强制.*复杂.*密码|限制.*登录|超时.*强制|自动.*登出|闪烁|跳转.*频繁'; $must = '权限|账户|认证|登录|口令|密码|双重|双因素|AD|安全|漏洞|扫描|系统日志|日志|审计|备份|恢复|容灾|冗余|时钟|NTP|同步|中断|稳定|性能|版本|升级|兼容|存储|校验|校对|一致|可靠|默认值|自动重连|心跳|故障自恢复'; $one = '查询|筛选|导出|统计|报表|曲线|历史|计算|策略|联动|控制|远程|北向|接口|API|ODCC|SNMP|MODBUS|Syslog|告警分级|告警屏蔽|确认|受理|模板|定时|阈值|显示时长|聚合|冲突|拓扑|溯源|存储策略|采集|接入|设备接入|标准|协议|下载|上传|批量|编辑|分页|标准化展示|实时|时序|多维|维度|分布式|模型|仿真'; $attr = '换肤|主题|皮肤|登录页|背景|美观|自定义|拖拽|大屏|组态|图元|三维|3D|矢量|摄像头|声光|语音|弹窗|颜色|动效|动画|缩放|U高指示|图标|可视化|热点|地图'; $indiff = '导航栏名称省略|IE9|360浏览器|popo|短信猫话费|信号强度查询|彩铃|铃声|占位|修订记录|BAK|菜单调整'; $matched=""; $cat=""; if($text -match $reverse){ $cat="Reverse"; $matched=$Matches[0] } elseif($text -match $must){ $cat="Must-be"; $matched=$Matches[0] } elseif($text -match $one){ $cat="One-dimensional"; $matched=$Matches[0] } elseif($text -match $attr){ $cat="Attractive"; $matched=$Matches[0] } elseif($text -match $indiff){ $cat="Indifferent"; $matched=$Matches[0] } else { $cat="One-dimensional"; $matched="default" } $x=0.6; $y=0.6; if($cat -eq "Must-be"){ $x=0.75; $y=0.25; if($text -match '安全|认证|密码|登录|漏洞|双因素|AD'){ $x=0.85; $y=0.2 } elseif($text -match '日志|审计'){ $x=0.65; $y=0.25 } elseif($text -match '备份|恢复|容灾|冗余|一致|可靠|存储|稳定|性能'){ $x=0.8; $y=0.3 } } elseif($cat -eq "One-dimensional"){ if($text -match '联动|策略|接口|API|ODCC|SNMP|MODBUS|控制|远程'){ $x=0.75; $y=0.75 } elseif($text -match '查询|筛选|导出|统计|报表|曲线|历史|告警屏蔽|告警分级|确认|受理'){ $x=0.6; $y=0.6 } elseif($text -match '采集|接入|设备接入|协议'){ $x=0.7; $y=0.7 } else { $x=0.65; $y=0.65 } } elseif($cat -eq "Attractive"){ $x=0.55; $y=0.82; if($text -match '登录页|换肤|主题|背景'){ $x=0.5; $y=0.75 } elseif($text -match '组态|图元|大屏|摄像头|三维|3D|可视化'){ $x=0.6; $y=0.85 } elseif($text -match '语音|声光|弹窗|颜色|动效|动画'){ $x=0.5; $y=0.8 } } elseif($cat -eq "Indifferent"){ $x=0.4; $y=0.4 } elseif($cat -eq "Reverse"){ $x=0.5; $y=0.15 } $j = Get-Jitter $text; $x = Clamp ($x + $j[0]); $y = Clamp ($y + $j[1]); return ,@($cat,$x,$y,$matched) }
$outRows = @()
foreach($r in $rows){ $bm=$r.业务模块; $mm=$r.功能模块; $fi=$r.功能项; $fp=$r.功能点; $res = Classify $fp; $outRows += [pscustomobject]@{ 业务模块=$bm; 功能模块=$mm; 功能项=$fi; 功能点=$fp; KANO类型=$res[0]; X=[double]$res[1]; Y=[double]$res[2]; 理由=$res[3] } }
$outRows | Export-Csv -Path $out -NoTypeInformation -Encoding UTF8
